permalink: /:title
url: "http://jslinterrors.com"

authors:
    jallardice:
        name: James Allardice
        avatar: https://gravatar.com/avatar/321be24529d43c2bacc7167337299e3d.png
        gplus: https://plus.google.com/110229746715330149995?rel=author
        twitter: james_allardice
        github: jamesallardice
        desc: "an enthusiastic young JavaScript developer at <a href='http://globalpersonals.co.uk/' target='_blank'>Global Personals</a> <em>(we're looking for developers so <a href='http://globaldev.co.uk/jobs' target='_blank'>please apply</a>)</em>. He is passionate about writing clean, maintainable JavaScript and uses JSHint every day to help achieve this."
    jklein:
        name: Jonathan Klein
        avatar: http://www.gravatar.com/avatar/72f8175ac13e367bb500dd4da1f1aa32.png
        gplus: https://plus.google.com/109491115907466487995?rel=author
        twitter: jonathanklein
        github: jklein
        desc: "Jonathan is a software engineer at Etsy, where he focuses on solving web performance and scalability challenges.  He started and organizes the Boston Web Performance Meetup Group, and he blogs regularly at <a href='http://www.jonathanklein.net'>www.jonathanklein.net</a>"
    fantasyshao:
        name: Chunhua Shao
        avatar: https://gravatar.com/avatar/2709dc7185e67863cb525bc365351db4.png